#ifndef __GENERATED_STATES__INCLUDE_GUARD
#define __GENERATED_STATES__INCLUDE_GUARD

#include <intrinsics.h>
#include <string.h>
#include <stdio.h>

// Import user libraries here (if any)
#include "adc.h"
#include "ble.h"
#include "stubs.h"
#include "i2c.h"
#include "oled.h"
#include "display_data.h"
#include "acc.h"
#include "ioint.h"
#include "leds.h"
#include "motor.h"
#include "pstore.h"
#include "rtc.h"
#include "globals.h"
#include "Timer1.h"

extern uint32 changeState;
extern uint32 stateDelay;
extern uint8  stateLevel_0;
extern uint8  stateLevel_1;
extern uint8  stateLevel_2;
extern uint8  stateLevel_3;
extern uint8  stateLevel_4;

extern const uint8 state_OTA;
void               state_OTA_execute      ( void );
void               state_OTA_setState     ( void );
void               state_OTA_transition   ( void );
void               state_OTA_finalization ( void );
extern const uint8 state_codeSpace;
void               state_codeSpace_execute      ( void );
void               state_codeSpace_setState     ( void );
void               state_codeSpace_transition   ( void );
void               state_codeSpace_finalization ( void );
extern const uint8 state_codeSpace_idle;
void               state_codeSpace_idle_execute      ( void );
void               state_codeSpace_idle_setState     ( void );
void               state_codeSpace_idle_transition   ( void );
void               state_codeSpace_idle_finalization ( void );
extern const uint8 state_codeSpace_DisplayInfo;
void               state_codeSpace_DisplayInfo_execute      ( void );
void               state_codeSpace_DisplayInfo_setState     ( void );
void               state_codeSpace_DisplayInfo_transition   ( void );
void               state_codeSpace_DisplayInfo_finalization ( void );
extern const uint8 state_codeSpace_DisplayInfo_DisplayTime;
void               state_codeSpace_DisplayInfo_DisplayTime_execute      ( void );
void               state_codeSpace_DisplayInfo_DisplayTime_setState     ( void );
void               state_codeSpace_DisplayInfo_DisplayTime_transition   ( void );
void               state_codeSpace_DisplayInfo_DisplayTime_finalization ( void );
extern const uint8 state_codeSpace_DisplayInfo_LowBatteryWarning;
void               state_codeSpace_DisplayInfo_LowBatteryWarning_execute      ( void );
void               state_codeSpace_DisplayInfo_LowBatteryWarning_setState     ( void );
void               state_codeSpace_DisplayInfo_LowBatteryWarning_transition   ( void );
void               state_codeSpace_DisplayInfo_LowBatteryWarning_finalization ( void );
extern const uint8 state_codeSpace_startIcon;
void               state_codeSpace_startIcon_execute      ( void );
void               state_codeSpace_startIcon_setState     ( void );
void               state_codeSpace_startIcon_transition   ( void );
void               state_codeSpace_startIcon_finalization ( void );
extern const uint8 state_system_on;
void               state_system_on_execute      ( void );
void               state_system_on_setState     ( void );
void               state_system_on_transition   ( void );
void               state_system_on_finalization ( void );
extern const uint8 state_system_on_Settings;
void               state_system_on_Settings_execute      ( void );
void               state_system_on_Settings_setState     ( void );
void               state_system_on_Settings_transition   ( void );
void               state_system_on_Settings_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime;
void               state_system_on_Settings_SettingTime_execute      ( void );
void               state_system_on_Settings_SettingTime_setState     ( void );
void               state_system_on_Settings_SettingTime_transition   ( void );
void               state_system_on_Settings_SettingTime_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime;
void               state_system_on_Settings_SettingTime_SettingTime_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime_SettingTenMinutes;
void               state_system_on_Settings_SettingTime_SettingTime_SettingTenMinutes_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingTenMinutes_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingTenMinutes_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingTenMinutes_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime_Setting_YearTens;
void               state_system_on_Settings_SettingTime_SettingTime_Setting_YearTens_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_YearTens_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_YearTens_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_YearTens_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime_Setting_Day;
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Day_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Day_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Day_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Day_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime_Setting_Month;
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Month_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Month_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Month_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Month_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime_Setting_Year;
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Year_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Year_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Year_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_Setting_Year_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime_SettingTimeFormat;
void               state_system_on_Settings_SettingTime_SettingTime_SettingTimeFormat_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingTimeFormat_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingTimeFormat_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingTimeFormat_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime_SettingHours;
void               state_system_on_Settings_SettingTime_SettingTime_SettingHours_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingHours_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingHours_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingHours_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SettingTime_SettingMinutes;
void               state_system_on_Settings_SettingTime_SettingTime_SettingMinutes_execute      ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingMinutes_setState     ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingMinutes_transition   ( void );
void               state_system_on_Settings_SettingTime_SettingTime_SettingMinutes_finalization ( void );
extern const uint8 state_system_on_Settings_SettingTime_SetTimeInit;
void               state_system_on_Settings_SettingTime_SetTimeInit_execute      ( void );
void               state_system_on_Settings_SettingTime_SetTimeInit_setState     ( void );
void               state_system_on_Settings_SettingTime_SetTimeInit_transition   ( void );
void               state_system_on_Settings_SettingTime_SetTimeInit_finalization ( void );
extern const uint8 state_system_on_Settings_PairMx2plus;
void               state_system_on_Settings_PairMx2plus_execute      ( void );
void               state_system_on_Settings_PairMx2plus_setState     ( void );
void               state_system_on_Settings_PairMx2plus_transition   ( void );
void               state_system_on_Settings_PairMx2plus_finalization ( void );
extern const uint8 state_system_on_Settings_PairMx2plus_PairMx2plusInit;
void               state_system_on_Settings_PairMx2plus_PairMx2plusInit_execute      ( void );
void               state_system_on_Settings_PairMx2plus_PairMx2plusInit_setState     ( void );
void               state_system_on_Settings_PairMx2plus_PairMx2plusInit_transition   ( void );
void               state_system_on_Settings_PairMx2plus_PairMx2plusInit_finalization ( void );
extern const uint8 state_system_on_Settings_PairMx2plus_PairingMx2plus;
void               state_system_on_Settings_PairMx2plus_PairingMx2plus_execute      ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plus_setState     ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plus_transition   ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plus_finalization ( void );
extern const uint8 state_system_on_Settings_PairMx2plus_PairingMx2plusFailed;
void               state_system_on_Settings_PairMx2plus_PairingMx2plusFailed_execute      ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plusFailed_setState     ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plusFailed_transition   ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plusFailed_finalization ( void );
extern const uint8 state_system_on_Settings_PairMx2plus_PairingMx2plusDone;
void               state_system_on_Settings_PairMx2plus_PairingMx2plusDone_execute      ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plusDone_setState     ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plusDone_transition   ( void );
void               state_system_on_Settings_PairMx2plus_PairingMx2plusDone_finalization ( void );
extern const uint8 state_system_on_Settings_DeviceInfo;
void               state_system_on_Settings_DeviceInfo_execute      ( void );
void               state_system_on_Settings_DeviceInfo_setState     ( void );
void               state_system_on_Settings_DeviceInfo_transition   ( void );
void               state_system_on_Settings_DeviceInfo_finalization ( void );
extern const uint8 state_system_on_Settings_DeviceInfo_DisplayVersion;
void               state_system_on_Settings_DeviceInfo_DisplayVersion_execute      ( void );
void               state_system_on_Settings_DeviceInfo_DisplayVersion_setState     ( void );
void               state_system_on_Settings_DeviceInfo_DisplayVersion_transition   ( void );
void               state_system_on_Settings_DeviceInfo_DisplayVersion_finalization ( void );
extern const uint8 state_system_on_Settings_DeviceInfo_DisplayErrorType;
void               state_system_on_Settings_DeviceInfo_DisplayErrorType_execute      ( void );
void               state_system_on_Settings_DeviceInfo_DisplayErrorType_setState     ( void );
void               state_system_on_Settings_DeviceInfo_DisplayErrorType_transition   ( void );
void               state_system_on_Settings_DeviceInfo_DisplayErrorType_finalization ( void );
extern const uint8 state_system_on_Settings_DeviceInfo_init;
void               state_system_on_Settings_DeviceInfo_init_execute      ( void );
void               state_system_on_Settings_DeviceInfo_init_setState     ( void );
void               state_system_on_Settings_DeviceInfo_init_transition   ( void );
void               state_system_on_Settings_DeviceInfo_init_finalization ( void );
extern const uint8 state_system_on_Settings_DeviceInfo_DisplayError;
void               state_system_on_Settings_DeviceInfo_DisplayError_execute      ( void );
void               state_system_on_Settings_DeviceInfo_DisplayError_setState     ( void );
void               state_system_on_Settings_DeviceInfo_DisplayError_transition   ( void );
void               state_system_on_Settings_DeviceInfo_DisplayError_finalization ( void );
extern const uint8 state_system_on_Settings_PairPhone;
void               state_system_on_Settings_PairPhone_execute      ( void );
void               state_system_on_Settings_PairPhone_setState     ( void );
void               state_system_on_Settings_PairPhone_transition   ( void );
void               state_system_on_Settings_PairPhone_finalization ( void );
extern const uint8 state_system_on_Settings_PairPhone_PairPhoneInit;
void               state_system_on_Settings_PairPhone_PairPhoneInit_execute      ( void );
void               state_system_on_Settings_PairPhone_PairPhoneInit_setState     ( void );
void               state_system_on_Settings_PairPhone_PairPhoneInit_transition   ( void );
void               state_system_on_Settings_PairPhone_PairPhoneInit_finalization ( void );
extern const uint8 state_system_on_Settings_PairPhone_PairingPhone;
void               state_system_on_Settings_PairPhone_PairingPhone_execute      ( void );
void               state_system_on_Settings_PairPhone_PairingPhone_setState     ( void );
void               state_system_on_Settings_PairPhone_PairingPhone_transition   ( void );
void               state_system_on_Settings_PairPhone_PairingPhone_finalization ( void );
extern const uint8 state_system_on_Settings_PairPhone_PairingPhoneFailed;
void               state_system_on_Settings_PairPhone_PairingPhoneFailed_execute      ( void );
void               state_system_on_Settings_PairPhone_PairingPhoneFailed_setState     ( void );
void               state_system_on_Settings_PairPhone_PairingPhoneFailed_transition   ( void );
void               state_system_on_Settings_PairPhone_PairingPhoneFailed_finalization ( void );
extern const uint8 state_system_on_Settings_PairPhone_PairingPhoneDone;
void               state_system_on_Settings_PairPhone_PairingPhoneDone_execute      ( void );
void               state_system_on_Settings_PairPhone_PairingPhoneDone_setState     ( void );
void               state_system_on_Settings_PairPhone_PairingPhoneDone_transition   ( void );
void               state_system_on_Settings_PairPhone_PairingPhoneDone_finalization ( void );
extern const uint8 state_system_on_Settings_exit;
void               state_system_on_Settings_exit_execute      ( void );
void               state_system_on_Settings_exit_setState     ( void );
void               state_system_on_Settings_exit_transition   ( void );
void               state_system_on_Settings_exit_finalization ( void );
extern const uint8 state_system_on_Settings_VerScrolling;
void               state_system_on_Settings_VerScrolling_execute      ( void );
void               state_system_on_Settings_VerScrolling_setState     ( void );
void               state_system_on_Settings_VerScrolling_transition   ( void );
void               state_system_on_Settings_VerScrolling_finalization ( void );
extern const uint8 state_system_on_Settings_SettingInit;
void               state_system_on_Settings_SettingInit_execute      ( void );
void               state_system_on_Settings_SettingInit_setState     ( void );
void               state_system_on_Settings_SettingInit_transition   ( void );
void               state_system_on_Settings_SettingInit_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions;
void               state_system_on_Settings_SetSmartDriveOptions_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_ScrollOut;
void               state_system_on_Settings_SetSmartDriveOptions_ScrollOut_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_ScrollOut_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_ScrollOut_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_ScrollOut_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_ScrollIn;
void               state_system_on_Settings_SetSmartDriveOptions_ScrollIn_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_ScrollIn_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_ScrollIn_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_ScrollIn_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_Init;
void               state_system_on_Settings_SetSmartDriveOptions_Init_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_Init_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_Init_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_Init_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_VerScrolling;
void               state_system_on_Settings_SetSmartDriveOptions_VerScrolling_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_VerScrolling_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_VerScrolling_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_VerScrolling_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_Back;
void               state_system_on_Settings_SetSmartDriveOptions_Back_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_Back_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_Back_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_Back_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed;
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_Warn;
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_Warn_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_Warn_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_Warn_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_Warn_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SetMaxSpeedInit;
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SetMaxSpeedInit_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SetMaxSpeedInit_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SetMaxSpeedInit_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SetMaxSpeedInit_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SettingMaxSpeed;
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SettingMaxSpeed_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SettingMaxSpeed_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SettingMaxSpeed_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetMaxSpeed_SettingMaxSpeed_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetAcceleration;
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_Warn;
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_Warn_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_Warn_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_Warn_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_Warn_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SetAccelInit;
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SetAccelInit_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SetAccelInit_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SetAccelInit_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SetAccelInit_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SettingAccel;
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SettingAccel_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SettingAccel_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SettingAccel_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetAcceleration_SettingAccel_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetControlMode;
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetControlMode_Warn;
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_Warn_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_Warn_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_Warn_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_Warn_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingEZMode;
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingEZMode_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingEZMode_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingEZMode_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingEZMode_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetControlMode_init;
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_init_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_init_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_init_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_init_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingControlMode;
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingControlMode_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingControlMode_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingControlMode_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetControlMode_SettingControlMode_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity;
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_Warn;
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_Warn_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_Warn_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_Warn_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_Warn_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SetTapSensInit;
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SetTapSensInit_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SetTapSensInit_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SetTapSensInit_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SetTapSensInit_finalization ( void );
extern const uint8 state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SettingTapSensitivity;
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SettingTapSensitivity_execute      ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SettingTapSensitivity_setState     ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SettingTapSensitivity_transition   ( void );
void               state_system_on_Settings_SetSmartDriveOptions_SetTapSensitivity_SettingTapSensitivity_finalization ( void );
extern const uint8 state_system_on_Settings_SetUnits;
void               state_system_on_Settings_SetUnits_execute      ( void );
void               state_system_on_Settings_SetUnits_setState     ( void );
void               state_system_on_Settings_SetUnits_transition   ( void );
void               state_system_on_Settings_SetUnits_finalization ( void );
extern const uint8 state_system_on_Settings_SetUnits_SettingUnits;
void               state_system_on_Settings_SetUnits_SettingUnits_execute      ( void );
void               state_system_on_Settings_SetUnits_SettingUnits_setState     ( void );
void               state_system_on_Settings_SetUnits_SettingUnits_transition   ( void );
void               state_system_on_Settings_SetUnits_SettingUnits_finalization ( void );
extern const uint8 state_system_on_Settings_SetUnits_init;
void               state_system_on_Settings_SetUnits_init_execute      ( void );
void               state_system_on_Settings_SetUnits_init_setState     ( void );
void               state_system_on_Settings_SetUnits_init_transition   ( void );
void               state_system_on_Settings_SetUnits_init_finalization ( void );
extern const uint8 state_system_on_idle;
void               state_system_on_idle_execute      ( void );
void               state_system_on_idle_setState     ( void );
void               state_system_on_idle_transition   ( void );
void               state_system_on_idle_finalization ( void );
extern const uint8 state_system_on_ScanForApp;
void               state_system_on_ScanForApp_execute      ( void );
void               state_system_on_ScanForApp_setState     ( void );
void               state_system_on_ScanForApp_transition   ( void );
void               state_system_on_ScanForApp_finalization ( void );
extern const uint8 state_system_on_startIcon;
void               state_system_on_startIcon_execute      ( void );
void               state_system_on_startIcon_setState     ( void );
void               state_system_on_startIcon_transition   ( void );
void               state_system_on_startIcon_finalization ( void );
extern const uint8 state_system_on_PowerAssistToggle;
void               state_system_on_PowerAssistToggle_execute      ( void );
void               state_system_on_PowerAssistToggle_setState     ( void );
void               state_system_on_PowerAssistToggle_transition   ( void );
void               state_system_on_PowerAssistToggle_finalization ( void );
extern const uint8 state_system_on_DisplayInfo;
void               state_system_on_DisplayInfo_execute      ( void );
void               state_system_on_DisplayInfo_setState     ( void );
void               state_system_on_DisplayInfo_transition   ( void );
void               state_system_on_DisplayInfo_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_Display_Battery;
void               state_system_on_DisplayInfo_Display_Battery_execute      ( void );
void               state_system_on_DisplayInfo_Display_Battery_setState     ( void );
void               state_system_on_DisplayInfo_Display_Battery_transition   ( void );
void               state_system_on_DisplayInfo_Display_Battery_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_LowBatteryWarning;
void               state_system_on_DisplayInfo_LowBatteryWarning_execute      ( void );
void               state_system_on_DisplayInfo_LowBatteryWarning_setState     ( void );
void               state_system_on_DisplayInfo_LowBatteryWarning_transition   ( void );
void               state_system_on_DisplayInfo_LowBatteryWarning_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_Display_Estimate_Distance;
void               state_system_on_DisplayInfo_Display_Estimate_Distance_execute      ( void );
void               state_system_on_DisplayInfo_Display_Estimate_Distance_setState     ( void );
void               state_system_on_DisplayInfo_Display_Estimate_Distance_transition   ( void );
void               state_system_on_DisplayInfo_Display_Estimate_Distance_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_DisplayTime;
void               state_system_on_DisplayInfo_DisplayTime_execute      ( void );
void               state_system_on_DisplayInfo_DisplayTime_setState     ( void );
void               state_system_on_DisplayInfo_DisplayTime_transition   ( void );
void               state_system_on_DisplayInfo_DisplayTime_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_pushIcon;
void               state_system_on_DisplayInfo_pushIcon_execute      ( void );
void               state_system_on_DisplayInfo_pushIcon_setState     ( void );
void               state_system_on_DisplayInfo_pushIcon_transition   ( void );
void               state_system_on_DisplayInfo_pushIcon_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_pushes;
void               state_system_on_DisplayInfo_pushes_execute      ( void );
void               state_system_on_DisplayInfo_pushes_setState     ( void );
void               state_system_on_DisplayInfo_pushes_transition   ( void );
void               state_system_on_DisplayInfo_pushes_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_DistanceIcon;
void               state_system_on_DisplayInfo_DistanceIcon_execute      ( void );
void               state_system_on_DisplayInfo_DistanceIcon_setState     ( void );
void               state_system_on_DisplayInfo_DistanceIcon_transition   ( void );
void               state_system_on_DisplayInfo_DistanceIcon_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_Distance;
void               state_system_on_DisplayInfo_Distance_execute      ( void );
void               state_system_on_DisplayInfo_Distance_setState     ( void );
void               state_system_on_DisplayInfo_Distance_transition   ( void );
void               state_system_on_DisplayInfo_Distance_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_coastIcon;
void               state_system_on_DisplayInfo_coastIcon_execute      ( void );
void               state_system_on_DisplayInfo_coastIcon_setState     ( void );
void               state_system_on_DisplayInfo_coastIcon_transition   ( void );
void               state_system_on_DisplayInfo_coastIcon_finalization ( void );
extern const uint8 state_system_on_DisplayInfo_coastTime;
void               state_system_on_DisplayInfo_coastTime_execute      ( void );
void               state_system_on_DisplayInfo_coastTime_setState     ( void );
void               state_system_on_DisplayInfo_coastTime_transition   ( void );
void               state_system_on_DisplayInfo_coastTime_finalization ( void );
extern const uint8 state_system_on_ShowSpeed;
void               state_system_on_ShowSpeed_execute      ( void );
void               state_system_on_ShowSpeed_setState     ( void );
void               state_system_on_ShowSpeed_transition   ( void );
void               state_system_on_ShowSpeed_finalization ( void );
extern const uint8 state_sleep;
void               state_sleep_execute      ( void );
void               state_sleep_setState     ( void );
void               state_sleep_transition   ( void );
void               state_sleep_finalization ( void );
extern const uint8 state_Sys_init;
void               state_Sys_init_execute      ( void );
void               state_Sys_init_setState     ( void );
void               state_Sys_init_transition   ( void );
void               state_Sys_init_finalization ( void );

#endif // __GENERATED_STATES__INCLUDE_GUARD
